version: "3.9"

services:
  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment-gateway
    command: [ "postgres", "-c", "log_statement=all" ]

  api:
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    environment:
      - DB_DSN=postgres://postgres:password@postgres:5432/payment-gateway?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  swagger:
    image: swaggerapi/swagger-ui:v4.4.0
    environment:
      - SWAGGER_JSON=/swagger-config.yaml
    volumes:
      - ./api/openapi-spec/api.yaml:/swagger-config.yaml
    ports:
      - "80:8080"
