/*
Payment Gateway API

Payment gateway API for merchants usage.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// AuthorizeRequestCardExpiration struct for AuthorizeRequestCardExpiration
type AuthorizeRequestCardExpiration struct {
	Month *int32 `json:"month,omitempty"`
	Year  *int32 `json:"year,omitempty"`
}

// NewAuthorizeRequestCardExpiration instantiates a new AuthorizeRequestCardExpiration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizeRequestCardExpiration() *AuthorizeRequestCardExpiration {
	this := AuthorizeRequestCardExpiration{}
	return &this
}

// NewAuthorizeRequestCardExpirationWithDefaults instantiates a new AuthorizeRequestCardExpiration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizeRequestCardExpirationWithDefaults() *AuthorizeRequestCardExpiration {
	this := AuthorizeRequestCardExpiration{}
	return &this
}

// GetMonth returns the Month field value if set, zero value otherwise.
func (o *AuthorizeRequestCardExpiration) GetMonth() int32 {
	if o == nil || o.Month == nil {
		var ret int32
		return ret
	}
	return *o.Month
}

// GetMonthOk returns a tuple with the Month field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizeRequestCardExpiration) GetMonthOk() (*int32, bool) {
	if o == nil || o.Month == nil {
		return nil, false
	}
	return o.Month, true
}

// HasMonth returns a boolean if a field has been set.
func (o *AuthorizeRequestCardExpiration) HasMonth() bool {
	if o != nil && o.Month != nil {
		return true
	}

	return false
}

// SetMonth gets a reference to the given int32 and assigns it to the Month field.
func (o *AuthorizeRequestCardExpiration) SetMonth(v int32) {
	o.Month = &v
}

// GetYear returns the Year field value if set, zero value otherwise.
func (o *AuthorizeRequestCardExpiration) GetYear() int32 {
	if o == nil || o.Year == nil {
		var ret int32
		return ret
	}
	return *o.Year
}

// GetYearOk returns a tuple with the Year field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizeRequestCardExpiration) GetYearOk() (*int32, bool) {
	if o == nil || o.Year == nil {
		return nil, false
	}
	return o.Year, true
}

// HasYear returns a boolean if a field has been set.
func (o *AuthorizeRequestCardExpiration) HasYear() bool {
	if o != nil && o.Year != nil {
		return true
	}

	return false
}

// SetYear gets a reference to the given int32 and assigns it to the Year field.
func (o *AuthorizeRequestCardExpiration) SetYear(v int32) {
	o.Year = &v
}

func (o AuthorizeRequestCardExpiration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Month != nil {
		toSerialize["month"] = o.Month
	}
	if o.Year != nil {
		toSerialize["year"] = o.Year
	}
	return json.Marshal(toSerialize)
}

type NullableAuthorizeRequestCardExpiration struct {
	value *AuthorizeRequestCardExpiration
	isSet bool
}

func (v NullableAuthorizeRequestCardExpiration) Get() *AuthorizeRequestCardExpiration {
	return v.value
}

func (v *NullableAuthorizeRequestCardExpiration) Set(val *AuthorizeRequestCardExpiration) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizeRequestCardExpiration) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizeRequestCardExpiration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizeRequestCardExpiration(val *AuthorizeRequestCardExpiration) *NullableAuthorizeRequestCardExpiration {
	return &NullableAuthorizeRequestCardExpiration{value: val, isSet: true}
}

func (v NullableAuthorizeRequestCardExpiration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizeRequestCardExpiration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
